export const STREAM_START_ACTION = "STREAM_START";
export const STREAM_STOP_ACTION = "STREAM_STOP";
export const ASSET_ARRIVED_ACTION = "ASSET_ARRIVED";
export const ASSET_MAP_ARRIVED_ACTION = "ASSET_MAP_ARRIVED";
